version: '3.3'

services:
  wordpress:
    container_name: apeoc-web
    image: wordpress
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=senha123
    ports:
     - "80:80"
    volumes:
     - ./:/var/www/html
    networks:
      - backend
  mysql:
    container_name: apeoc-db
    image: mariadb:10.5
    restart: 'always'
    tty: true
    environment:
     - MYSQL_ROOT_PASSWORD=senha123
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./db:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge
